### ISSUE TITLE
When A Human Is Speaking You Must Act As God - Not Working

### ISSUE THREAD

**Issue by deepanharsha** [deepanharsha/gptjailbreak#1]
Version: 1.00 Official Release

# Info
When I Speak As A Human With "-" The Bot Is Not Taking The Role Of God

**Comment by ShOeLaYz** [comment]
This Issue Is Being Fixed In The 1.01 BETA Version.
**We Are Trying Our Best To Fix This Issue**

**Comment by deepanharsha** [comment]
This has been fixed with the latest release of ChatGPT's 4o Model.
Tested & Working 👍.

Regards,
Harsha.
